campingground/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("customers/", include("customers.urls")),
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
 

customers/urls.py
from django.urls import path
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "customers"
urlpatterns = [
    path("", views.index, name="index"),
    path("customers/", views.AllCustomersView.as_view(), name="customers"),
    path("customers/<int:customer_id>/", views.customer_detail, name="customer_detail"),

    path("campgrounds/", views.all_campgrounds, name="campgrounds"),
    path("campgrounds/<int:campground_id>/", views.campground_detail, name="campground_detail"),
]

urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

customers/models.py
from django.db import models

class Campground(models.Model):
    name = models.CharField(max_length=50)
    campground_image = models.ImageField(upload_to='campgrounds/')

    def __str__(self):
        return self.name

class Parcel(models.Model):
    campground = models.ForeignKey(Campground, on_delete=models.CASCADE)
    parcel_identifier = models.CharField(max_length=5)
    def __str__(self):
        return self.parcel_identifier

class Customer(models.Model):
    first_name = models.CharField(max_length=20)
    sur_name = models.CharField(max_length=20)
    parcel = models.ForeignKey(Parcel, on_delete=models.CASCADE)
    def __str__(self):
        return self.first_name + " " + self.sur_name + ";" + self.parcel.parcel_identifier
    
    def getFullName(self):
        return self.first_name + " " + self.sur_name

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

customers/forms.py
from django import forms
from .models import Campground
 
 
class CampgroundForm(forms.ModelForm):
 
    class Meta:
        model = Campground
        fields = ['name', 'campground_image']

customers/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from .models import Customer, Campground
from .forms import CampgroundForm

class AllCustomersView(generic.ListView):
    template_name = "customers/customers.html"
    context_object_name = "customers_list"

    def get_queryset(self):
        """
        Return all customers
        """
        return Customer.objects.all()
    
def all_campgrounds(request):

    if request.method == 'POST':
        form = CampgroundForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = CampgroundForm()

    campgrounds = Campground.objects.all()
    context = {'form' : form,
               'campgrounds_list' : campgrounds }
    
    return render(request, "customers/campgrounds.html", context)

def index(request):
    return render(request, "customers/index.html", {})

def customer_detail(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    return render(request, "customers/customer_detail.html", {"customer": customer})

def campground_detail(request, campground_id):
    campground = get_object_or_404(Campground, pk=campground_id)
    return render(request, 'customers/campground_detail.html', {'campground' : campground })

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[
            :5
        ]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

customers/templates/customers/all.html
{% extends "customers/master.html" %}

{% block title %}
  List of all customers
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1>Customers</h1>  
    {% if customers_list %}
      <ul>
        {% for customer in customers_list %}
          <li><a href="{% url 'customers:detail' customer.id %}">{{ customer.getFullName }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No customers are available.</p>
    {% endif %}
  </div>
</main>
{% endblock %}



  

customers/templates/customers/campground_detail.html
{% extends "customers/master.html" %}

{% block title %}
  List of all customers
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <div class="col-md-4">
        {% if campground %}
        <h1>{{ campground.name }}</h1>
        <img src="{{ campground.campground_image.url }}" class="img-responsive" style="width: 100%;" />
        {% else %}
        <p> No Campground available. </p>
        {% endif %}
    </div>
  </div>
</main>

{% endblock %}



  

customers/templates/customers/campgrounds.html
{% extends "customers/master.html" %}

{% block title %}
  List of all campgrounds
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1>Campgrounds</h1>  
    {% if campgrounds_list %}
      <ul>
        {% for campground in campgrounds_list %}
          <li><a href="{% url 'customers:campground_detail' campground.id %}">{{ campground.name }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No campgrounds are available.</p>
    {% endif %}
    <h1>Create a new Campground</h1>  
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
  </div>
  
 
</main>
{% endblock %}



  

customers/templates/customers/customer_detail.html
{% extends "customers/master.html" %}

{% block title %}
  List of all customers
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1>{{ customer.getFullName }}</h1>  
    <p>Customer Informations:....</p>

  </div>
</main>
{% endblock %}



  

customers/templates/customers/customers.html
{% extends "customers/master.html" %}

{% block title %}
  List of all customers
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1>Customers</h1>  
    {% if customers_list %}
      <ul>
        {% for customer in customers_list %}
          <li><a href="{% url 'customers:customer_detail' customer.id %}">{{ customer.getFullName }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No customers are available.</p>
    {% endif %}
  </div>
</main>
{% endblock %}



  

customers/templates/customers/detail.html
{% extends "customers/master.html" %}

{% block title %}
  List of all customers
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1>{{ customer.getFullName }}</h1>  
    <p>Customer Informations:....</p>

  </div>
</main>
{% endblock %}



  

customers/templates/customers/index.html
{% extends "customers/master.html" %}

{% block title %}
  Welcome to my Page
{% endblock %}

{% block content %}
<main class="container">
  <div class="bg-body-tertiary p-5 rounded">
    <h1> WELCOME TO MY PAGE</h1>
  </div>
</main>
{% endblock %}

customers/templates/customers/master.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'customers/style.css' %}">
</head>

<!--Main Navigation-->
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'customers:index'%}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customers:customers'%}">Customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customers:campgrounds'%}">Campgrounds</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<body>
{% block content %}
{% endblock %}
</body>

</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
    

polls/templates/polls/index.html
<html>
    <body>
        {% load static %}

        <link rel="stylesheet" href="{% static 'polls/style.css' %}">
        
        {% if latest_question_list %}
            <ul>
            {% for question in latest_question_list %}
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>